/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.MiModelo;
import java.util.ArrayList;
import java.util.Vector;
import modelo.Mensaje;
import modelo.Usuario;

/**
 *
 * @author dam
 */
public class PanelBandeja extends javax.swing.JPanel {

    Usuario logueado;
    MiModelo modelo;

    public PanelBandeja(Usuario logueado) {

        initComponents();
        this.logueado = logueado;
        //CLASE NUESTRA QUE HEREDA DE DEFAULTTABLEMODEL
        modelo = new MiModelo();
        //
        configurarTabla();
        mostrarMensajes();

    }

    private void configurarTabla() {

        String[] titulos = {"EMISOR", "ASUNTO", "LEIDO", "FECHA"};
        modelo.setColumnIdentifiers(titulos);
        tblMensajes.setModel(modelo);

    }

    private void mostrarMensajes() {

        ArrayList<Mensaje> mensajes = logueado.getbEntrada();

        for (Mensaje m : mensajes) {

            Vector v = new Vector();
            v.add(m.getEmisor().getEmail());
            v.add(m.getAsunto());
            v.add(m.isLeido());
            v.add(m.getFecha().fechaCorta());
            modelo.addRow(v);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensajes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        chkLeido = new javax.swing.JCheckBox();

        tblMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMensajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMensajes);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEXTO");

        txtTexto.setEditable(false);
        txtTexto.setBackground(new java.awt.Color(255, 255, 255));
        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        jScrollPane2.setViewportView(txtTexto);

        chkLeido.setBackground(new java.awt.Color(0, 0, 0));
        chkLeido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkLeido.setForeground(new java.awt.Color(255, 255, 255));
        chkLeido.setText("LEIDO");
        chkLeido.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkLeidoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(chkLeido)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLeido)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMensajesMouseClicked
        int fila = tblMensajes.rowAtPoint(evt.getPoint());
        Mensaje m = logueado.getbEntrada().get(fila);
        txtTexto.setText(m.getContenido());
        //PARA QUE SE MARQUE AUTOMÁTICAMENTE COMO LEIDO
        logueado.actualizarCorreo(fila, true);
        chkLeido.setSelected(true);

    }//GEN-LAST:event_tblMensajesMouseClicked

    private void chkLeidoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkLeidoStateChanged

        int fila = tblMensajes.getSelectedRow();
        //PONEMOS EL IF PARA QUE NO FALLE EN CASO DE NO HABER MENSAJES
        if (fila != -1) {
            //DE ESTA FORMA PODEMOS DESMARCAR O MARCAR EL CHECKBOX Y GUARDAR EL CAMBIO
            logueado.actualizarCorreo(fila, chkLeido.isSelected());
            tblMensajes.setValueAt(chkLeido.isSelected(), fila, 2);
        }
    }//GEN-LAST:event_chkLeidoStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkLeido;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMensajes;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
